- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    aws_key_name: "{{ lookup('env', 'AWS_KEY_NAME') }}"
    aws_security_group: "{{ lookup('env', 'AWS_SECURITY_GROUP') }}"
    aws_instance_type: "{{ lookup('env', 'AWS_BUILD_INSTANCE_TYPE') }}"
    aws_ami_name: "kubevirt-centos-v0-11-0-2-build-1"
    aws_region: "{{ lookup('env', 'AWS_REGION') }}"
    aws_subnet_id: "{{ lookup('env', 'AWS_SUBNET_ID') }}"
  tasks:
    - name: find amis
      ec2_ami_facts:
        filters:
          name: "{{ aws_ami_name }}"
        region: "{{ item }}"
      register: ami_ids
      with_items:
        - us-east-1
        - us-east-2
        # - us-west-1
        - us-west-2
        - ap-northeast-1
        - ap-northeast-2
        - ap-south-1
        - ap-southeast-1
        - ap-southeast-2
        - ca-central-1
        - eu-central-1
        - eu-west-1
        - eu-west-2
        - eu-west-3
        - sa-east-1

    - debug: var=ami_ids

    # - debug: var="{{ item.images[0].image_id }}"
    #   with_items: "{{ ami_ids.results }}"

    - name: delete AMIs
      ec2_ami:
        image_id: "{{ item.images[0].image_id }}"
        delete_snapshot: True
        state: absent
        region: "{{ item.item }}"
      with_items: "{{ ami_ids.results }}"
