- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    gcp_instance_name: "{{ lookup('env', 'IMAGE_NAME') }}"
    credentials_file: "{{ lookup('env', 'GOOGLE_APPLICATION_CREDENTIALS') }}"
    project_id: "{{ lookup('env', 'PROJECT_ID') }}"
    zone: "{{ lookup('env', 'ZONE') }}"
    service_account_email:  "{{ lookup('env', 'SERVICE_ACCOUNT_EMAIL') }}"
  tasks:
    - name: Stop the test instance
      gce:
         instance_names: "{{ gcp_instance_name }}"
         zone: "{{ zone }}"
         image: kubevirt-button
         state: stopped
         service_account_email: "{{ service_account_email }}"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"

    - name: Delete the test instance
      gce:
         instance_names: "{{ gcp_instance_name }}"
         zone: "{{ zone }}"
         image: kubevirt-button
         state: absent
         service_account_email: "{{ service_account_email }}"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"
